sudo: required
services:
  - docker

before_install:
  - docker build -t talipcank/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true talipcank/react-test npm run test

after_success:
  - docker build -t talipcank/multi-client ./client
  - docker build -t talipcank/multi-nginx ./nginx
  - docker build -t talipcank/multi-server ./server
  - docker build -t talipcank/multi-worker ./worker
  # Log in the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push talipcank/multi-client
  - docker push talipcank/multi-nginx
  - docker push talipcank/multi-server
  - docker push talipcank/multi-worker

language: generic